- name: Create a cluster 
  shell: |
    export GOOGLE_APPLICATION_CREDENTIALS={{ playbook_dir }}/plan/auth/mykubernetesproject-285821-f95be9f750e5.json
    cd {{ playbook_dir }}/plan;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform init -backend-config "bucket={{ terraform['%s' | format(env)].bucket }}";
    terraform plan -var-file=env.tfvars;
    terraform apply -var-file=env.tfvars -auto-approve -refresh=true
  when: (operation == "create")