
- name: Destroy a cluster 
  shell: |
    export GOOGLE_APPLICATION_CREDENTIALS={{ playbook_dir }}/plan/{{ terraform['%s' | format(env)].credentials }}
    cd {{ playbook_dir }}/plan;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform destroy -var-file=env.tfvars -auto-approve
  when: (operation == "destroy")