- name: Manage cluster 
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "{{ playbook_dir }}/plan/{{ terraform[ '%s' | format(env)].credentials }}"
  terraform:
    project_path: "{{ playbook_dir }}/plan"
    workspace: "{{ env }}"
    state: "{{ operation }}"
  register: terraform_result
  when: operation is defined

- name: Add cluster to kubectl
  command: "gcloud container clusters get-credentials {{ terraform[ '%s' | format(env)].cluster_name }} --region {{ terraform[ '%s' | format(env)].region }} --project {{ terraform[ '%s' | format(env)].project }}"
  when: terraform_result is defined and not terraform_result.failed and operation is defined and operation != "absent"
  register: kubectl_credentials

- name: Set default namespace
  command: kubectl config set-context --current --namespace=default
  when: not kubectl_credentials.skipped
