apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: cameornwhite/quotes-back:v1
        name: api
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: mysql-password
        - name: SQLALCHEMY_DATABASE_URI
          value: "mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@data:3306/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: 
    api-load-balancer 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: api
  type: LoadBalancer  
