version: "3"
services:
  back:
    image: cameornwhite/quotes-back:v1
    ports:
      - "3000:3000"
    networks:
      - myapp
  data:
    image: cameornwhite/quotes-data:v1
    container_name: data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root" 
      MYSQL_ROOT_PASSWORD: "root" 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks: 
      myapp:

networks:
  myapp: