apiVersion: v1
kind: Service
metadata:
  name: api-node-port 
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30000
    protocol: TCP